name: Package Theme

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clean workspace
      run: |
        rm -Rf dist/

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Version
      id: set_version
      run: |
        echo "::set-env name=PACKAGE_VERSION::1.0.$GITHUB_RUN_NUMBER"
        echo "::set-env name=PACKAGE_NAME::theme-m20-1.0.$GITHUB_RUN_NUMBER"
    
    - name: Package
      id: package
      run: |
        mkdir dist
        ls -Al
        pwd
        cp -R src/* dist/
        cp pack.json dist/
        sed -i "s/{version}/$PACKAGEVERSION/g" "dist/pack.json"
    
    - name: Create artifact
      id: create_artifect
      uses: montudor/action-zip@v0.1.0
      with: 
        args: zip -qq -r -j  ${{ env.PACKAGE_NAME }}.zip ./dist
    
    - name: Upoad Artifect
      id: upload_artifects
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.PACKAGE_NAME }}.zip
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.PACKAGE_NAME }}
        release_name: Release ${{ env.PACKAGE_NAME }}
        body: "Theme"
        draft: false
        prerelease: false
    
    - name: Upload Release
      id: upload_release 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.PACKAGE_NAME }}.zip
        asset_name: ${{ env.PACKAGE_NAME }}.zip
        asset_content_type: application/zip